services:
  redis:
    image: redis:alpine3.20
    container_name: redis
    ports:
      - "26379:26379"  # 映射 Redis 端口
    command: ["redis-server", "--port", "26379"]
    networks:
      - my_network

  mysql:
    image: mysql:8.0.39
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"  # 设置 MySQL root 密码
      MYSQL_DATABASE: "mydatabase"  # 创建一个数据库（可选）
      MYSQL_USER: "user"  # 设置一个 MySQL 用户
      MYSQL_PASSWORD: "123456"  # 设置 MySQL 用户密码
    ports:
      - "23306:3306"  # 映射 MySQL 端口
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql  # 持久化 MySQL 数据

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
