server:
  host: "192.168.1.4"
  port: 8080
  name: "user-srv"

mysql:
  host: "192.168.1.4"
  port: 23306
  dbName: "mxshop"
  username: "root"
  password: "123456"

consul:
  host: "192.168.1.4"
  port: 8500
  name: "user-srv"
  tag:
    - "user-srv"
    - "go"
